version: '3.8'
services:
  web:
    build: .
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    command: yarn start